package util;

public enum TransitionEffect implements MarqueeEffect
{
    RANDOM_LIGHT, FADE, SPLIT_SCROLL_HORIZONTAL, SPLIT_SCROLL_VERTICAL,
    HALF_SCROLL_TOP_LEFT, HALF_SCROLL_TOP_RIGHT, HALF_SCROLL_LEFT_UP, HALF_SCROLL_LEFT_DOWN,
}
